name: Workflow for labeling
on: [pull_request_review]

jobs:
  labeling:
    name: Labeling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - run: npm install @actions/github @actions/core
      - name: replace approved label with change-request label
        uses: ./.github/actions/pull-request-labels
        with:
          approval_labels_to_delete: 'レビュアー待ち,主役待ち,レビュー中'
          approval_labels_to_add: 'レビュー完了'
          request_change_labels_to_delete: 'レビュー完了,レビュアー待ち'
          request_change_labels_to_add: 'レビュー中,主役待ち'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
